### ISSUE TITLE
Could we fuses in electron at the moment?

### ISSUE THREAD

**Issue by phamminhvu** [electron/fuses#1]
Hi Team,

We tried to follow the instruction for installing the library "fuses" to our electron project? 
We used electron version 12.x.x
But looks like It is not ready to use yet.

Thank you very much for feedback!

Best regards,
Jason

**Comment by MarshallOfSound** [comment]
Spamming the `electron` org, mentioning me repetitively or otherwise abusing our issue tracker is not an appropriate way to interact with OSS.  Please avoid doing so.

In regards to this issue, if you have a bug, please raise a bug with details and repro steps.  Questions such "does this work", "how do we use this" or "is this maintained" are simply unnecessary and a waste of maintainer time.
